language: node_js
node_js: stable

cache:
  directories:
  - node_modules

env:
- DICTIONARY_URL=$DICTIONARY_URL

before_deploy:
- "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
