language: node_js
node_js: stable

env:
  - CLOUDFLARE_ZONE_ID=$CLOUDFLARE_ZONE_ID
  - CLOUDFLARE_AUTH_TOKEN=$CLOUDFLARE_AUTH_TOKEN

cache:
  directories:
    - node_modules

before_deploy:
  - npm run generateDictionary
  - npm run build
after_deploy:
  - npm run purgeCloudflareCache

script:
  - npm test
  - npm run coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
