language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - npm run generateDictionary
  - npm run build
after_deploy:
  - |
    curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache" \
     -H "Authorization: Bearer ${CLOUDFLARE_AUTH_TOKEN}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

script:
  - npm test
  - npm run coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
