name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  generate-dictionary:
    name: Generate dictionary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Generate dictionary
        run: npm run generateDictionary

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

  build-and-deploy-demo:
    name: Create demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: pr-number-action
        id: pr_number
        uses: kkak10/pr-number-action@v1.3

      - run: echo "PR number is ${{ steps.pr_number.outputs.pr }}"

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Build
        env:
          DEMO: true
          NODE_ENV: production
          BASE_URL: /${{ steps.pr_number.outputs.pr }}/
        run: |
          npm run generateDictionary
          npx webpack

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
          allow_empty_commit: true

      - name: Purge cache on Cloudflare
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CF_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CF_AUTH_TOKEN }}
          PURGE_URLS: '["https://interslavic-dictionary.com/${{ steps.pr_number.outputs.pr }}/*"]'

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://interslavic-dictionary.com/${{ steps.pr_number.outputs.pr }}/
          environment: production
