name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: |
          npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Test
        run: |
          npm run test

  generate-dictionary:
    name: Generate dictionary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Generate dictionary
        run: |
          npm run generateDictionary

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Build
        run: |
          npm run build

  coveralls:
    name: Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Test
        run: |
          npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
